### ISSUE TITLE
Mesitersinger spells missing

### ISSUE THREAD

**Issue by sorviel** [UnearthedArcana/Might_and_Guile#28]
Hello,

Just installed the latest version of MnG. This is the only mod I have, and have installed all components from it.

The Meistersinger class does not have the druid spells in the spellbook, but the core Silence / Vocalize / Command etc... from the base Bard.

Any idea on why this is happening?

**Comment by subtledoctor** [comment]
Working as intended. They are not in your spellbook because you don’t need to memorize them, they are considered slways memorized. So memorize some other stuff, sleep, let the system do its thing for 2 seconds when you wake up. Then press the ‘cast spell’ button - your Meistersinger spells will be there.
